version: '2'

services:
  api:
    image: blindsidenetwks/scalelite:v1-api
    container_name: scalelite-v1-api
    entrypoint: /srv/scalelite/bin/start
    env_file: scalelite.env
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    #volumes:
    #  - ./recordings:/var/bigbluebutton
    links:
      - db
      - redis
  poller:
    image: blindsidenetwks/scalelite:v1-api
    container_name: scalelite-v1-poller
    entrypoint: /srv/scalelite/bin/start-poller
    env_file: scalelite.env
    restart: always
    links:
      - db
      - redis
  db:
    image: postgres:9.5
    restart: always
    expose:
      - '5432'
    volumes:
      - ./scalelite/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scalelite
      - POSTGRES_USER=scalelite
      - POSTGRES_PASSWORD=scalelite
  redis:
    image: redis
    restart: always
    ports:
      - 127.0.0.1:56379:6379
    volumes:
      - ./scalelite/redis:/data
